/* =========================================================================
 * Nexus Backend API (index.js)
 * 
 * The main Express server routing requests from the React frontend.
 * Handles:
 * 1. Serving static audio files (.mp3s generated by ElevenLabs)
 * 2. Supplying the database of papers to the client feed
 * 3. Processing manual DOI submissions via Crossref + Gemini + ElevenLabs
 * ========================================================================= */
const express = require('express');
const cors = require('cors');
const fs = require('fs');
const path = require('path');
const axios = require('axios');
require('dotenv').config({ path: path.join(__dirname, '../.env') });

const { normalizePaperData } = require('./services/crossref');
const { generateInsights } = require('./services/llm');
const { generateSpeech } = require('./services/tts');

const app = express();
const PORT = process.env.PORT || 3001;
const DB_PATH = path.join(__dirname, '../data/database.json');
const AUDIO_DIR = path.join(__dirname, '../data/audio');

// Middleware
app.use(cors()); // Allow requests from the Vite frontend (port 5173)
app.use(express.json()); // Parse incoming JSON payloads

// Static Route: Serve generated audio files directly
app.use('/api/audio', express.static(AUDIO_DIR));

/* -------------------------------------------------------------------------
 * GET /api/papers
 * Reads the local `database.json` and supports optional discipline/search filtering.
 * ------------------------------------------------------------------------- */
app.get('/api/papers', (req, res) => {
    try {
        if (!fs.existsSync(DB_PATH)) {
            return res.json([]);
        }
        const data = fs.readFileSync(DB_PATH, 'utf-8');
        const today = new Date();
        today.setHours(23, 59, 59, 999);

        let papers = JSON.parse(data)
            .map(p => ({ reviewStatus: p.reviewStatus || 'peerReviewed', ...p }))
            // Only serve papers that are published (past date) and peer-reviewed
            .filter(p => {
                if (!p.publishDate) return false;
                const pub = new Date(p.publishDate);
                if (isNaN(pub.getTime()) || pub > today) return false;
                if (p.reviewStatus === 'preReview') return false;
                return true;
            });

        const { discipline, search, limit } = req.query;

        if (discipline) {
            papers = papers.filter(p => p.discipline.toLowerCase() === discipline.toLowerCase());
        }

        if (search) {
            const q = search.toLowerCase();
            papers = papers.filter(p =>
                (p.title || '').toLowerCase().includes(q) ||
                (p.summary || '').toLowerCase().includes(q) ||
                (p.authors || []).join(' ').toLowerCase().includes(q)
            );
        }

        if (limit) {
            const max = parseInt(limit, 10);
            if (!isNaN(max) && max > 0) {
                papers = papers.slice(0, max);
            }
        }

        res.json(papers);
    } catch (error) {
        console.error('Error reading database:', error);
        res.status(500).json({ error: 'Failed to retrieve papers' });
    }
});

/* -------------------------------------------------------------------------
 * POST /api/papers/:id/audio
 * On-demand ElevenLabs audio generator for a specific paper.
 * ------------------------------------------------------------------------- */
app.post('/api/papers/:id/audio', async (req, res) => {
    const { id } = req.params;
    if (!id) return res.status(400).json({ error: 'Paper ID required' });

    try {
        if (!fs.existsSync(DB_PATH)) {
            return res.status(404).json({ error: 'Database not initialized' });
        }

        const data = fs.readFileSync(DB_PATH, 'utf-8');
        const papers = JSON.parse(data);
        const paperIndex = papers.findIndex(p => p.id === id || p.doi === id);

        if (paperIndex === -1) {
            return res.status(404).json({ error: 'Paper not found in database' });
        }

        const paper = papers[paperIndex];

        // If audio already exists, return immediately
        if (paper.audioUrl && fs.existsSync(path.join(__dirname, '..', paper.audioUrl.replace('/api/', 'data/')))) {
            return res.json({ message: 'Audio already exists', audioUrl: paper.audioUrl });
        }

        if (!fs.existsSync(AUDIO_DIR)) {
            fs.mkdirSync(AUDIO_DIR, { recursive: true });
        }

        const audioFilename = `${paper.id.replace(/[^a-zA-Z0-9]/g, '_')}.mp3`;
        const audioPath = path.join(AUDIO_DIR, audioFilename);
        const textToRead = `${paper.title}. Summary: ${paper.summary} Why it matters: ${paper.significance}`;

        console.log(`Generating on-demand audio for paper: ${paper.id}...`);
        const hasAudio = await generateSpeech(textToRead, audioPath);

        if (!hasAudio) {
            return res.status(500).json({ error: 'Audio generation failed or ElevenLabs key missing' });
        }

        const audioUrl = `/api/audio/${audioFilename}`;
        papers[paperIndex].audioUrl = audioUrl;
        fs.writeFileSync(DB_PATH, JSON.stringify(papers, null, 2), 'utf-8');

        res.json({ message: 'Audio generated successfully', audioUrl });
    } catch (error) {
        console.error('Error generating on-demand audio:', error);
        res.status(500).json({ error: 'Audio generation failed', details: error.message });
    }
});


/* -------------------------------------------------------------------------
 * POST /api/submit
 * Description: The core ingestion pipeline for a single user-submitted DOI.
 * Flow:
 * 1. Validates DOI
 * 2. Fetches raw abstract/metadata from Crossref API
 * 3. Sends abstract to Gemini AI to generate accessible 'insights'
 * 4. Sends Gemini's insights to ElevenLabs to generate an `.mp3` narration
 * 5. Saves `.mp3` to disk and updates `database.json`
 * ------------------------------------------------------------------------- */
app.post('/api/submit', async (req, res) => {
    const { doi } = req.body;
    if (!doi) {
        return res.status(400).json({ error: 'DOI is required for submission.' });
    }

    try {
        console.log(`Received manual submission for DOI: ${doi}`);
        // Step 1: Fetch raw JSON from Crossref database using the provided DOI
        const response = await axios.get(`https://api.crossref.org/works/${encodeURIComponent(doi)}`);
        if (response.status !== 200 || !response.data.message) {
            return res.status(404).json({ error: 'DOI not found in Crossref database.' });
        }

        // Step 2: Clean the raw JSON into our standardized Nexus object schema
        const rawItem = response.data.message;
        const normalized = normalizePaperData(rawItem);

        // Pre-check: Many papers on Crossref hit paywalls and hide their abstract.
        if (!normalized.abstract) {
            return res.status(400).json({ error: 'Abstract not available for this DOI, cannot generate insights. (Paywalled)' });
        }

        // Step 3: Pass standardized object to Gemini for LLM synthesis
        const processedPaper = await generateInsights(normalized);
        if (!processedPaper) {
            return res.status(500).json({ error: 'Failed to process insights.' });
        }

        // Step 4: Pass the synthesized text to ElevenLabs for Audio Generation
        console.log(`Generating audio narration for remote submission ${processedPaper.id}...`);

        // Clean the ID to make a safe filesystem filename
        const audioFilename = `${processedPaper.id.replace(/[^a-zA-Z0-9]/g, '_')}.mp3`;
        const audioPath = path.join(AUDIO_DIR, audioFilename);

        // The script it will read (Title, Summary, Significance)
        const textToRead = `${processedPaper.title}. Summary: ${processedPaper.summary} Why it matters: ${processedPaper.significance}`;

        // Wait for ElevenLabs API to physically write the .mp3 file to `audioPath`
        const hasAudio = await generateSpeech(textToRead, audioPath);
        if (hasAudio) {
            // Give the frontend the static mount point to find the file (keep it host-agnostic)
            processedPaper.audioUrl = `/api/audio/${audioFilename}`;
        }

        // Step 5: Save payload to Database
        let existingData = [];
        if (fs.existsSync(DB_PATH)) {
            existingData = JSON.parse(fs.readFileSync(DB_PATH, 'utf-8'));
        }

        // Prevent exact duplicates using the DOI/id string
        if (!existingData.some(p => p.id === processedPaper.id)) {
            existingData.unshift(processedPaper); // add to top of feed
            fs.writeFileSync(DB_PATH, JSON.stringify(existingData, null, 2), 'utf-8');
        }

        // Return the fully hydrated paper object so the React feed can append it instantly in-memory
        res.json({ message: 'Paper successfully analyzed and added to Nexus!', paper: processedPaper });
    } catch (error) {
        console.error('Error in manual submission:', error.message);
        res.status(500).json({ error: 'Failed to submit paper.', details: error.message });
    }
});

/* -------------------------------------------------------------------------
 * POST /api/ingest
 * Description: Trigger the background mass-ingestion script. 
 * Responds immediately while spinning up a background thread to process 
 * bulk papers from Crossref.
 * ------------------------------------------------------------------------- */
app.post('/api/ingest', async (req, res) => {
    const { runIngestion } = require('./scripts/ingest');
    try {
        // Run asynchronously so we don't block the HTTP response
        runIngestion().catch(e => console.error("Background ingestion failed", e));
        res.json({ message: 'Ingestion pipeline started in the background.' });
    } catch {
        res.status(500).json({ error: 'Failed to start ingestion' });
    }
});

app.listen(PORT, () => {
    console.log(`Nexus Backend API running on http://localhost:${PORT}`);
});
